# Generated by Django 4.2.7 on 2023-11-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissions',
            old_name='permission',
            new_name='name',
        ),
    ]
