# Generated by Django 4.2.7 on 2023-11-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_orderservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='standard_value',
            field=models.FloatField(default=0.0),
        ),
    ]
