# Generated by Django 4.2.7 on 2023-11-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_orderproducts'),
        ('service_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='os_products', to='product.orderproducts'),
        ),
    ]
