# Generated by Django 4.2.7 on 2023-11-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0002_serviceorder_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='products_total_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='services_total_value',
            field=models.FloatField(default=0.0),
        ),
    ]
