# Generated by Django 4.2.7 on 2023-11-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0003_serviceorder_products_total_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(default='Pendente', max_length=255),
        ),
    ]
