# Generated by Django 4.2.7 on 2023-11-21 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0007_serviceorder_installments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='status',
        ),
    ]
