# Generated by Django 4.2.7 on 2023-11-23 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplier_document'),
        ('product', '0004_product_purchase_price'),
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'purchase_order_status',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='comments',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_supplier', to='supplier.supplier'),
        ),
        migrations.AlterModelTable(
            name='purchaseorder',
            table='purchase_order',
        ),
        migrations.CreateModel(
            name='PurchaseOrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order', models.BigIntegerField()),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aux_product', to='product.product')),
            ],
            options={
                'db_table': 'aux_purchase_order_products',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='products',
            field=models.ManyToManyField(related_name='po_products', to='purchase_order.purchaseorderproducts'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_status', to='purchase_order.purchaseorderstatus'),
        ),
    ]
