# Generated by Django 4.2.7 on 2023-11-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_purchaseorder_created_at_purchaseorder_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproducts',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
