# Generated by Django 4.2.7 on 2023-11-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0005_alter_purchaseorder_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproducts',
            name='purchase_order',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
