# Generated by Django 4.2.7 on 2023-11-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_birth_date_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
