# Generated by Django 4.2.7 on 2023-11-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_type',
            new_name='type',
        ),
    ]
