# Generated by Django 4.2.7 on 2023-11-08 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_birth_date_client_gender'),
        ('vehicle', '0002_rename_vehicle_type_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_owner', to='client.client'),
        ),
    ]
