# Generated by Django 4.2.7 on 2023-11-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_measure_unit',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0.0)),
                ('brand', models.CharField(max_length=255)),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_measure_unit', to='product.productmeasureunit')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_type', to='product.producttype')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
