# Generated by Django 4.2.7 on 2023-11-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_orderproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(default=0.0),
        ),
    ]
