# Generated by Django 4.2.7 on 2023-11-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='document',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
