# Generated by Django 4.2.7 on 2024-03-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='financialentry',
            table='financial_entry',
        ),
    ]
